Repository sepandhaghighi/nafas, pull requests merged in 2024-08, with the labels that each got.

#90 Refactor
  .github/dependabot.yml
  CHANGELOG.md
  nafas/functions.py
Labels: minor, refactor

#92 Exit message
  CHANGELOG.md
  nafas/__main__.py
  nafas/params.py
Labels: enhancement

#93 Add Silence to Sounds
  CHANGELOG.md
  nafas/sounds/exhale.wav
  nafas/sounds/inhale.wav
  nafas/sounds/preparing.wav
  nafas/sounds/retain.wav
  nafas/sounds/start.wav
  nafas/sounds/sustain.wav
  nafas/sounds/well_done.wav
Labels: enhancement

#95 Version 0.7
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  NAFAS.spec
  README.md
  SECURITY.md
  nafas/params.py
  otherfiles/Version.rc
  otherfiles/version_check.py
  setup.py
Labels: release

#98 Feature/clean screen function
  .github/workflows/test.yml
  AUTHORS.md
  CHANGELOG.md
  nafas/__main__.py
  nafas/functions.py
  otherfiles/version_check.py
  test/test.py
Labels: enhancement
