Repository sepandhaghighi/nafas, pull requests merged in 2024-07, with the labels that each got.

#79 `playsound` -> `nava`
  .github/workflows/test.yml
  CHANGELOG.md
  dev-requirements.txt
  nafas/functions.py
  requirements.txt
  test/test.py
Labels: enhancement

#81 `README.md` modification
  AUTHORS.md
  README.md
Labels: documentation, minor

#82 SECURITY.md
  CHANGELOG.md
  SECURITY.md
  otherfiles/version_check.py
Labels: documentation, minor

#83 Release instructions
  otherfiles/RELEASE.md
Labels: documentation, minor

#85 Build system modification
  CHANGELOG.md
  NAFAS.spec
  otherfiles/RELEASE.md
  otherfiles/version_check.py
Labels: enhancement, test

#87 Test system modification
  .github/workflows/test.yml
  README.md
  autopep8.bat
  autopep8.sh
  dev-requirements.txt
  otherfiles/version_check.py
  setup.cfg
Labels: documentation, test

#88 Sound bug
  nafas/__main__.py
  nafas/functions.py
  nafas/params.py
  test/test.py
Labels: bug, test

#89 Modern Templates for Issue and Pull Requests
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  CHANGELOG.md
  otherfiles/RELEASE.md
  otherfiles/version_check.py
Labels: documentation, enhancement
