Repository sepandhaghighi/nafas, pull requests merged in 2025-07, with the labels that each got.

#157 New Speakers (`ca1` and `ca2`)
  CHANGELOG.md
  README.md
  nafas/params.py
  nafas/sounds/ca1/exhale.wav
  nafas/sounds/ca1/inhale.wav
  nafas/sounds/ca1/preparing.wav
  nafas/sounds/ca1/retain.wav
  nafas/sounds/ca1/start.wav
  nafas/sounds/ca1/sustain.wav
  nafas/sounds/ca1/well_done.wav
  nafas/sounds/ca2/exhale.wav
  nafas/sounds/ca2/inhale.wav
  nafas/sounds/ca2/preparing.wav
  nafas/sounds/ca2/retain.wav
  nafas/sounds/ca2/start.wav
  nafas/sounds/ca2/sustain.wav
  nafas/sounds/ca2/well_done.wav
  test/test.py
Labels: enhancement

#160 Refactor
  CHANGELOG.md
  README.md
  nafas/__main__.py
  nafas/functions.py
  test/test.py
Labels: refactor

#161 Refactor
  CHANGELOG.md
  nafas/functions.py
Labels: refactor

#162 Refactor
  CHANGELOG.md
  nafas/__main__.py
  nafas/functions.py
  test/test.py
Labels: refactor

#163 Minor edits
  README.md
  setup.py
Labels: documentation
