Repository sepandhaghighi/nafas, pull requests merged in 2025-01, with the labels that each got.

#117 Menu
  CHANGELOG.md
  nafas/__main__.py
  nafas/functions.py
  nafas/params.py
  test/test.py
Labels: documentation, minor

#118 Cite
  README.md
  nafas/functions.py
  nafas/params.py
  test/test.py
Labels: documentation, minor

#119 Version 0.9
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  NAFAS.spec
  README.md
  SECURITY.md
  nafas/params.py
  otherfiles/Version.rc
  otherfiles/version_check.py
  setup.py
Labels: release

#120 Calming3 program
  CHANGELOG.md
  PROGRAMS.md
  nafas/params.py
  test/test.py
Labels: new feature

#121 `README.md` update
  CHANGELOG.md
  README.md
Labels: documentation

#123 Cite
  README.md
Labels: documentation

#124 Overview Figure Added to Readme
  README.md
  otherfiles/overview.png
Labels: documentation
