Repository sepandhaghighi/nafas, pull requests merged in 2025-06, with the labels that each got.

#148 Version 1.2
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  NAFAS.spec
  README.md
  SECURITY.md
  nafas/params.py
  otherfiles/Version.rc
  otherfiles/version_check.py
  setup.py
  test/test.py
Labels: release

#149 New Speakers (US2 + Indian1/2)
  CHANGELOG.md
  MANIFEST.in
  nafas/__main__.py
  nafas/functions.py
  nafas/params.py
  nafas/sounds/in1/exhale.wav
  nafas/sounds/in1/inhale.wav
  nafas/sounds/in1/preparing.wav
  nafas/sounds/in1/retain.wav
  nafas/sounds/in1/start.wav
  nafas/sounds/in1/sustain.wav
  nafas/sounds/in1/well_done.wav
  nafas/sounds/in2/exhale.wav
  nafas/sounds/in2/inhale.wav
  nafas/sounds/in2/preparing.wav
  nafas/sounds/in2/retain.wav
  nafas/sounds/in2/start.wav
  nafas/sounds/in2/sustain.wav
  nafas/sounds/in2/well_done.wav
  nafas/sounds/us1/exhale.wav
  nafas/sounds/us1/inhale.wav
  nafas/sounds/us1/preparing.wav
  nafas/sounds/us1/retain.wav
  nafas/sounds/us1/start.wav
  nafas/sounds/us1/sustain.wav
  nafas/sounds/us1/well_done.wav
  nafas/sounds/us2/exhale.wav
  nafas/sounds/us2/inhale.wav
  nafas/sounds/us2/preparing.wav
  nafas/sounds/us2/retain.wav
  nafas/sounds/us2/start.wav
  nafas/sounds/us2/sustain.wav
  nafas/sounds/us2/well_done.wav
  test/test.py
Labels: enhancement

#150 New Speakers (`cn1` and `cn2`)
  CHANGELOG.md
  nafas/params.py
  nafas/sounds/cn1/exhale.wav
  nafas/sounds/cn1/inhale.wav
  nafas/sounds/cn1/preparing.wav
  nafas/sounds/cn1/retain.wav
  nafas/sounds/cn1/start.wav
  nafas/sounds/cn1/sustain.wav
  nafas/sounds/cn1/well_done.wav
  nafas/sounds/cn2/exhale.wav
  nafas/sounds/cn2/inhale.wav
  nafas/sounds/cn2/preparing.wav
  nafas/sounds/cn2/retain.wav
  nafas/sounds/cn2/start.wav
  nafas/sounds/cn2/sustain.wav
  nafas/sounds/cn2/well_done.wav
  test/test.py
Labels: enhancement

#151 Speakers Information Added to The Readme
  CHANGELOG.md
  README.md
Labels: documentation
